version: '3.9'
services:
  client1:
    build: . 
    volumes: 
      - ./client_results:/client_results
    environment:
      - CLIENT1=1
  client2:
    build: . 
    volumes: 
      - ./client_results:/client_results
    environment:
      - CLIENT2=1

